<h1>Numpy in python</h1>

NumPy is a python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.



In [1]:
import numpy as np

arr=np.array([1,2,3,4,5])

In [2]:
print(arr)

[1 2 3 4 5]


In [3]:
lst=['Ashish','Hello','Hi']
arr1=np.array(lst)

In [4]:
print(arr1)

['Ashish' 'Hello' 'Hi']


In [5]:
np.__version__

'1.17.0'

In [6]:
print(np.__version__)

1.17.0


In [7]:
type(arr)

numpy.ndarray

In [8]:
type(arr1)

numpy.ndarray

In [9]:
tp=(1,2,3,4,5)
x=np.array(tp)

print(x)

[1 2 3 4 5]


# Dimension of Arrays

0-D array : [23]<br>
1-D array : [1,2,3,4,5]<br>
2-D array : [[1,2],[3,4]]<br>
3-D array : [[[1,2],[3,4]]  ,  [[5,6],[7,8]]]<br>

In [10]:
d0=np.array(23)
d1=np.array([1,2,3,4,5])
d2=np.array([[1,2],[3,4]])
d3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

<b> ndim : </b> to count the dimension of an array

In [11]:
print(d0.ndim)
print(d1.ndim)
print(d2.ndim)
print(d3.ndim)

0
1
2
3


Higher Dimensional arrays using <b> ndmin attribute </b>

In [12]:
dh=np.array([1,2,3,4,5],ndmin=5)
print(dh)
print(dh.ndim)

[[[[[1 2 3 4 5]]]]]
5


# Indexing

Indexing in numpy arrays starts with 0 not 1.


In [13]:
print(d1)
print(d1[0])
print(d1[1])
print(d1[2])
print(d1[3])
print(d1[4])

[1 2 3 4 5]
1
2
3
4
5


In [14]:
print(arr[5])

IndexError: index 5 is out of bounds for axis 0 with size 5

<b> NOTE : </b>as our array starts with 0 it end with 4 (length=5), so when we are accessing arr[5] it is giving an error named <b> out of bound</b> exception 

------------------------------------------------------------------------------------------------------------------------------------------------<br><b>indexing 2d arrays</b>

In [15]:
print(d2)
print(d2[0,0])
print(d2[0,1])
print(d2[1,0])
print(d2[1,1])

[[1 2]
 [3 4]]
1
2
3
4


------------------------------------------------------------------------------------------------------------------------------------------------<br><b>indexing 3d arrays</b>

In [16]:
print(d3)
print(d3[0,0,0])
print(d3[0,0,1])
print(d3[0,1,0])
print(d3[0,1,1])

print(d3[1,0,0])
print(d3[1,0,1])
print(d3[1,1,0])
print(d3[1,1,1])


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1
2
3
4
5
6
7
8


------------------------------------------------------------------------------------------------------------------------------------------------<br><b>negative indexing in a numpy array</b>

In [17]:
print(d2)
print(d2[1,-1])
print(d2[0,-2])

[[1 2]
 [3 4]]
4
1


# Slicing in numpy 

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [18]:
arr=[23,34,45,56,67]

In [19]:
arr[1:4] #without steps that means steps=1

[34, 45, 56]

In [20]:
arr[0:4:2] #with steps

[23, 45]

In [21]:
arr[:3] #without start means start=0

[23, 34, 45]

In [22]:
arr[2:] #without end means end=length

[45, 56, 67]

<b> Negative slicing </b>

In [23]:
arr[-5:-2]  #it prints the value from -5 to -2 index

[23, 34, 45]

In [24]:
arr[-2:-5]  #it cannot print in reverse formatn that from back to front

[]

# Numpy DataTypes

By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. eg. "ABCD" <br>
integer - used to represent integer numbers. eg. -1, 2, 3<br>
float - used to represent real numbers. eg. 1.2, 42.42<br>
boolean - used to represent True or False.<br>
complex - used to represent a number in complex plain. eg. 1.0 + 2.0j, 1.5 + 2.5j<br>


NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.<br>

Below is a list of all data types in NumPy and the characters used to represent them.<br>

i - integer<br>
b - boolean<br>
u - unsigned integer<br>
f - float<br>
c - complex float<br>
m - timedelta<br>
M - datetime<br>
O - object<br>
S - string<br>
U - unicode string<br>
V - fixed chunk of memory for other type ( void )<br>

<b>dtype:</b> print the datattype of a numpy array

In [25]:
arr1=np.array([1,2,3,4,5])
arr2=np.array(['A','B','C'])
arr3=np.array(["Apple","Banana","Grapes"])
arr4=np.array(["Hello world","You can see magics in python"])
arr5=np.array([1.0+2.0j, 1.5+2.5j])
arr6=np.array([2.4,4.8,6.7])

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
print(arr4.dtype)
print(arr5.dtype)
print(arr6.dtype)

int32
<U1
<U6
<U28
complex128
float64


<b>Your can see there is a number after the datatype characters</b><br>
that number is actually the size of that variable<br>
for example:
arr1 is of type int and of size 32<br>
in arr2 each elelement size id of 1byte<br>
similarly others goes on too.

<h3>Creating array with defined datatype

In [26]:
#let us say that we want to decalre an array of integer type
xint= np.array([1,2,3,4,5],dtype='i')
print(xint)

[1 2 3 4 5]


In [27]:
xstring= np.array([1,2,3,4,5],dtype='S')
print(xstring)
#because of the character S this array is of string type

[b'1' b'2' b'3' b'4' b'5']


In [28]:
xint4= np.array([100000,300000,400000,500000],dtype='i4')
print(xint4)
#here because we have used i4 in which i means integer and 4 means 4bytes of size  

[100000 300000 400000 500000]


In [29]:
#lets us what wil happen if we declare a character type elemt inside a integer type numpy array

x=np.array(['a',1,2,3],dtype='i')
print(x)

ValueError: invalid literal for int() with base 10: 'a'

so you can see it will arise an error as invalid literals

# Initial placeholders

In [30]:
x0= np.zeros((3,4))  #creating matrix of zeros when rows and columsn are passed as paraments
print(x0)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
x1=np.ones((5,3)) #create matrix of ones when rows and columns are passed
print(x1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [32]:
xr=np.random.random((2,3)) # random values are stored in matrix of size provided
print(xr)

[[0.75497413 0.69270684 0.1138077 ]
 [0.22742155 0.74614236 0.71008564]]


# Inspecting Arrays

<h3> Reshape </h3>

In [33]:
xr.shape

(2, 3)

In [34]:
xr.reshape(3,2)

array([[0.75497413, 0.69270684],
       [0.1138077 , 0.22742155],
       [0.74614236, 0.71008564]])

In [35]:
len(xr)

2

In [36]:
xr.size

6

# Array Mathematics

In [37]:
a=np.random.random((3,3))
#here we are using ((3,3))in place of (3,3) this is because random only take one arguement so we pass a set of 2values.
b=np.random.random((3,3))
print(a)
print(b)

[[0.36387366 0.98502268 0.94859999]
 [0.09330367 0.0420448  0.31302371]
 [0.09054858 0.32513882 0.03799239]]
[[0.16936641 0.72533809 0.51826011]
 [0.04245465 0.04824351 0.26421943]
 [0.58940031 0.47329526 0.18749549]]


In [38]:
#Multiplication
c=a*b
print(c)

[[0.06162797 0.71447447 0.49162154]
 [0.00396117 0.00202839 0.08270695]
 [0.05336936 0.15388666 0.0071234 ]]


In [39]:
#Addition
c=a+b
print(c)

[[0.53324007 1.71036077 1.4668601 ]
 [0.13575832 0.0902883  0.57724314]
 [0.67994889 0.79843408 0.22548788]]


In [40]:
#Subtraction
c=a-b
print(c)

[[ 0.19450725  0.25968459  0.43033988]
 [ 0.05084902 -0.00619871  0.04880429]
 [-0.49885173 -0.14815644 -0.14950309]]


In [41]:
#division
c=a/b
print(c)

[[2.14844052 1.35801868 1.83035501]
 [2.19772544 0.8715121  1.1847112 ]
 [0.15362833 0.68696827 0.20263098]]


we can also use different functions to achieve the same



In [42]:
#Multiplication
c=np.multiply(a,b)
print(c)

[[0.06162797 0.71447447 0.49162154]
 [0.00396117 0.00202839 0.08270695]
 [0.05336936 0.15388666 0.0071234 ]]


In [43]:
#Addition
c=np.add(a,b)
print(c)

[[0.53324007 1.71036077 1.4668601 ]
 [0.13575832 0.0902883  0.57724314]
 [0.67994889 0.79843408 0.22548788]]


In [44]:
#Subtraction
c=np.subtract(a,b)
print(c)

[[ 0.19450725  0.25968459  0.43033988]
 [ 0.05084902 -0.00619871  0.04880429]
 [-0.49885173 -0.14815644 -0.14950309]]


In [45]:
#Division
c=np.divide(a,b)
print(c)

[[2.14844052 1.35801868 1.83035501]
 [2.19772544 0.8715121  1.1847112 ]
 [0.15362833 0.68696827 0.20263098]]


<b> More arithmetic functions are : sin,exp,cos etc</b>

In [46]:
print(np.exp(a))

[[1.43889241 2.67787261 2.58209217]
 [1.09779505 1.0429412  1.36755396]
 [1.09477469 1.38422279 1.03872333]]


In [47]:
print(np.sqrt(a))

[[0.60321941 0.99248309 0.97396098]
 [0.3054565  0.20504828 0.55948522]
 [0.30091292 0.57020946 0.19491638]]


In [48]:
print(np.sin(b))

[[0.16855786 0.66338847 0.49536948]
 [0.0424419  0.04822479 0.26115586]
 [0.55586262 0.45582177 0.18639886]]


In [49]:
print(np.cos(a))

[[0.93452522 0.55284422 0.58282131]
 [0.99565037 0.99911625 0.95140681]
 [0.99590328 0.94760639 0.99927838]]


# Comparision 

In [50]:
a==b  #give us element wise comparision

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [51]:
c=[[1,2],[3,4]]
d=[[1,2],[3,4]]
c==d

True

In [52]:
c=[[1,2],[3,4]]
d=[[1,4],[3,4]]
c==d

False

In [53]:
print(np.array_equal(a,b)) #array wise check 

False


# Copying arrays

The Difference Between Copy and View<br>
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.<br>

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.<br>

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view<br>

<h2>View</h2>

In [54]:
a

array([[0.36387366, 0.98502268, 0.94859999],
       [0.09330367, 0.0420448 , 0.31302371],
       [0.09054858, 0.32513882, 0.03799239]])

In [55]:
view_a=a.view()

In [56]:
print(view_a)

[[0.36387366 0.98502268 0.94859999]
 [0.09330367 0.0420448  0.31302371]
 [0.09054858 0.32513882 0.03799239]]


<h2>Copy</h2>

In [57]:
a

array([[0.36387366, 0.98502268, 0.94859999],
       [0.09330367, 0.0420448 , 0.31302371],
       [0.09054858, 0.32513882, 0.03799239]])

In [58]:
copy_a= np.copy(a)

In [59]:
print(copy_a)

[[0.36387366 0.98502268 0.94859999]
 [0.09330367 0.0420448  0.31302371]
 [0.09054858 0.32513882 0.03799239]]


# Sorting arrays

In [60]:
a

array([[0.36387366, 0.98502268, 0.94859999],
       [0.09330367, 0.0420448 , 0.31302371],
       [0.09054858, 0.32513882, 0.03799239]])

In [61]:
a.sort()

In [62]:
a

array([[0.36387366, 0.94859999, 0.98502268],
       [0.0420448 , 0.09330367, 0.31302371],
       [0.03799239, 0.09054858, 0.32513882]])

we can see that each line is being sorted 

# Array Manipulation

<h3> Transposing </h3>

In [63]:
a

array([[0.36387366, 0.94859999, 0.98502268],
       [0.0420448 , 0.09330367, 0.31302371],
       [0.03799239, 0.09054858, 0.32513882]])

In [64]:
i=np.transpose(a) #this will transpose the matrix a
i

array([[0.36387366, 0.0420448 , 0.03799239],
       [0.94859999, 0.09330367, 0.09054858],
       [0.98502268, 0.31302371, 0.32513882]])

<h2>Note : </h2> <br>
<h3>There are tons of more functions available in numpy and practising each is kind of impossible to do but by this we can assume that the very core concept of numpy is clear by now...</h3><br>